-- T-Ride settlement confirmation flow.
-- Adds a booking state between dropoff QR scan and final completion.

SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE bookings MODIFY COLUMN status ENUM(
  'PENDING', 'CONFIRMED', 'DRIVER_ASSIGNED', 'ON_ROUTE', 'DRIVER_ARRIVED',
  'PICKED_UP', 'SETTLEMENT_PENDING', 'COMPLETED', 'CANCELLED', 'NO_SHOW'
) NOT NULL DEFAULT 'PENDING';

ALTER TABLE booking_status_logs MODIFY COLUMN from_status ENUM(
  'PENDING', 'CONFIRMED', 'DRIVER_ASSIGNED', 'ON_ROUTE', 'DRIVER_ARRIVED',
  'PICKED_UP', 'SETTLEMENT_PENDING', 'COMPLETED', 'CANCELLED', 'NO_SHOW'
) NULL DEFAULT NULL;

ALTER TABLE booking_status_logs MODIFY COLUMN to_status ENUM(
  'PENDING', 'CONFIRMED', 'DRIVER_ASSIGNED', 'ON_ROUTE', 'DRIVER_ARRIVED',
  'PICKED_UP', 'SETTLEMENT_PENDING', 'COMPLETED', 'CANCELLED', 'NO_SHOW'
) NOT NULL;
