module.exports = {
  VEHICLE_BASE: 'VEHICLE_BASE',
  NAME_SIGN: 'NAME_SIGN',
  NIGHT_SURCHARGE: 'NIGHT_SURCHARGE',
  AIRPORT_SURCHARGE: 'AIRPORT_SURCHARGE',
  TOLL_GATE: 'TOLL_GATE',
  HOLIDAY_SURCHARGE: 'HOLIDAY_SURCHARGE',
  WAITING_CHARGE: 'WAITING_CHARGE',
  OTHER: 'OTHER',
};
