const { FRESH_LOCATION_MS } = require('./driverLocation');

module.exports = {
  MAX_ACTIVE_JOBS: 1,
  ONLINE_REQUIRED: true,
  LOCATION_FRESH_REQUIRED: false,
  FRESH_LOCATION_MS,
  SCHEDULE_CONFLICT_WINDOW_MS: 2 * 60 * 60 * 1000,
  SCORE_WEIGHTS: {
    ONLINE: 20,
    NO_ACTIVE_JOB: 25,
    NEAR_PICKUP_MAX: 30,
    LOCATION_FRESH: 10,
    LOW_ASSIGNMENT_LOAD: 10,
    HIGH_RATING: 5,
  },
  NEAR_PICKUP_DISTANCE_KM: 15,
  RATING_THRESHOLD: 4.5,
  ASSIGNMENTS_TODAY_LOW_THRESHOLD: 2,
};
