module.exports = {
  FRESH_LOCATION_MS: 60_000,
  DRIVER_LOCATION_RATE_WINDOW_MS: 10_000,
  DRIVER_LOCATION_RATE_MAX: 6,
  TRACKABLE_BOOKING_STATUSES: new Set([
    'ON_ROUTE',
    'DRIVER_ARRIVED',
    'PICKED_UP',
  ]),
  TERMINAL_BOOKING_STATUSES: new Set([
    'COMPLETED',
    'CANCELLED',
    'NO_SHOW',
  ]),
};
