/**
 * constants/errorCodes.js — Aligns with OpenAPI ErrorCode enum
 */
module.exports = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  DUPLICATE_BOOKING: 'DUPLICATE_BOOKING',
  FLIGHT_NOT_FOUND: 'FLIGHT_NOT_FOUND',
  GOOGLE_PLACE_NOT_FOUND: 'GOOGLE_PLACE_NOT_FOUND',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  AUTH_INVALID: 'AUTH_INVALID',
  VEHICLE_NOT_SELECTABLE: 'VEHICLE_NOT_SELECTABLE',
  DRIVER_NOT_AVAILABLE: 'DRIVER_NOT_AVAILABLE',
  BOOKING_NOT_ACCESSIBLE: 'BOOKING_NOT_ACCESSIBLE',
  RATE_LIMIT: 'RATE_LIMIT',
  EXTERNAL_API_ERROR: 'EXTERNAL_API_ERROR',
};
