const NOTIFICATION_TYPES = {
  BOOKING_CREATED: 'BOOKING_CREATED',
  BOOKING_CONFIRMED: 'BOOKING_CONFIRMED',
  DRIVER_ASSIGNED: 'DRIVER_ASSIGNED',
  DRIVER_ARRIVED: 'DRIVER_ARRIVED',
  TRIP_PICKED_UP: 'TRIP_PICKED_UP',
  TRIP_COMPLETED: 'TRIP_COMPLETED',
  REVIEW_REQUESTED: 'REVIEW_REQUESTED',
  COMMISSION_REQUIRED: 'COMMISSION_REQUIRED',
  RECEIPT_SUBMITTED: 'RECEIPT_SUBMITTED',
  RECEIPT_REJECTED: 'RECEIPT_REJECTED',
  SETTLEMENT_APPROVED: 'SETTLEMENT_APPROVED',
  DRIVER_REASSIGNED: 'DRIVER_REASSIGNED',
  REVIEW_SUBMITTED: 'REVIEW_SUBMITTED',
  CHAT_MESSAGE_RECEIVED: 'CHAT_MESSAGE_RECEIVED',
};

module.exports = NOTIFICATION_TYPES;
