const OUTBOX_STATUS = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
};

const NOTIFICATION_AGGREGATE_TYPE = 'booking';

module.exports = {
  OUTBOX_STATUS,
  NOTIFICATION_AGGREGATE_TYPE,
};
